
library(htmltools)
library(shiny)
library(shinydashboard)
library(shinythemes)
library(ggplot2)
library(dygraphs)
library(forecast)
library(ISwR)
library(readxl)
library(dplyr)
library(MASS)
library(markdown)
library(QuantPsyc)
library(lubridate)
library(fmsb)
library(d3heatmap)
library(DAAG)
library(ggfortify)
library(metricsgraphics)
library(ggvis)
library(timeSeries)
library(fitdistrplus)
library(tictoc)
library(doParallel)
#library(RevoScaleR)
library(shinyBS)
#library(dynlm)
library(vars)
library(xts)
library(zoo)
#library(stringr)
library(GGally) 
library(plotly)
library(Quandl)

# Einbindung der Latex-Application als Voraussetzung der Generierung automatischer PDF-Reports
# sollte die Application auf andere Rechner gestreut werden, muss garantiert werdern, dass 
# pdflatex installiert ist.
# Sys.which('pdflatex')
# Sys.getenv('PATH')
# Sys.setenv(PATH=paste(Sys.getenv("PATH"),"C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin",sep=";"))

server <- function(input, output, session) {
  
  
  source("Server/sidebar.R", local = TRUE)
  source("lagFunctions.R", local = TRUE)
  source('Server/0.0.server_home.R', local=TRUE)
  source('Server/0.1.server_password.R', local=TRUE)
  source('Server/1.0.server_dataimport.R', local=TRUE)
  source('Server/1.1.server_mainsettings.R', local=TRUE)
  source('Server/2.1.server_datarearrange.R', local=TRUE)
  source('Server/2.2.server_datasplit.R', local=TRUE)
  source('Server/3.1.server_data_analysis.R', local=TRUE)
  source('Server/4.1.server_createRegressionmodel.R', local=TRUE)
  source('Server/4.2.server_impactAnalysis.R', local=TRUE)
  source('Server/4.3.server_modelValidation.R', local=TRUE)
  source('Server/5.1.server_forecastArima.R', local=TRUE)
  source('Server/5.2.server_forecastTrend.R', local=TRUE)
  source('Server/5.2.server_forecastTrend.R', local=TRUE)
  source('Server/5.3.server_forecastManual.R', local=TRUE)
  source('Server/5.4.server_forecastSavedModels.R', local=TRUE)
  source('Server/6.1.server_forecastAlgo.R', local=TRUE)
  source('Server/6.1.server_forecastFrame.R', local=TRUE)
  source('Server/7.server_forecastVar.R', local=TRUE)
  source('Server/8.1.server_backtesting.R', local=TRUE)
  source('Server/8.2.server_backtestingonestepahead.R', local=TRUE)
  source('Server/9.server_reporting.R', local=TRUE)
  
  
}