; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C7712E97-6A64-49F4-AFE0-CAC248C23434}
AppName=PAS
AppVersion=1.0
;AppVerName=PAS 1.0
AppPublisher=PricewaterhouseCoopers AG Wirtschaftsprüfungsgesellschaft
AppPublisherURL=http://www.pwc.de/
AppSupportURL=http://www.pwc.de/
AppUpdatesURL=http://www.pwc.de/
DefaultDirName={userpf}\PAS
DisableProgramGroupPage=yes
OutputDir=C:\Users\Administrator\Desktop\PAS-App
OutputBaseFilename=setup
SetupIconFile=C:\Users\Administrator\Desktop\PAS-App\PAS-App\shiny\Logo.ico
Compression=lzma
SolidCompression=yes
Encryption=yes
Password=Montecarlo1
LicenseFile=C:\Users\Administrator\Desktop\PAS-App\PAS-App\shiny\AGB_deutsch.rtf
PrivilegesRequired=lowest

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Administrator\Desktop\PAS-App\PAS-App\run.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Administrator\Desktop\PAS-App\PAS-App\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Dirs]
Name:"{app}\shiny"; Attribs: hidden system

[Icons]
Name: "{commonprograms}\PAS"; Filename: "{app}\run.exe"
Name: "{commondesktop}\PAS"; Filename: "{app}\run.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\run.exe"; Description: "{cm:LaunchProgram,PAS}"; Flags: shellexec postinstall skipifsilent

[Registry]
Check: IsWin64; Root: HKCU64; Subkey: "Software\PwC\PAS"; ValueType : string; ValueName: "InstallDate"; ValueData: "{code:DateTime}"; Flags: createvalueifdoesntexist
Root: HKCU; Subkey: "Software\PwC\PAS"; ValueType: string; ValueName: "InstallDate"; ValueData: "{code:DateTime}"; Flags: createvalueifdoesntexist

[Code]
function DateTime(dummy: String): String;
begin
  result:= GetDateTimeString('yyyymmdd', #0, #0);
end;
